# Web-appendix-TMLE-causal-inference-survival-analysis
* Web appendix 

This is the web-appendix to our manuscript entitled /On targeted/
/maximum likelihood estimation for causal inference in survival and
competing risks analysis/. \\

We provide =R= code to apply our current implementations of TMLE for
estimation of causal parameters in survival and competing risks
settings; this includes the iterative and the one-step targeting
procedures as well as super learning to combine different Cox
regression models or variations over the Poisson-based highly adaptive
lasso (HAL) estimator. \\

Although the current implementations can be applied to new data
setting, we emphasize that our implementations remain to be made into
a more user-friendly software package. Current and future work is
involved with this.

** Overview


*Note:* To run any of the code below you need to load the following
=R= script:

#+ATTR_LATEX: :options otherkeywords={}, deletekeywords={}
#+BEGIN_SRC R  :results none :exports code  :session *R* :cache yes  
source("./usage/load.R") 
#+END_SRC


** Data example 

In our manuscript we use the publicly available dataset =colon= from
the =survival= package in =R= as a running example. These are data
from a trial on adjuvant chemotherapy for colon cancer, comparing
levamisole treatment against levamisole treatment combined with
fluorouracil (a chemotherapy agent) against no treatment. 

The raw data available in R consist of two rows per subject:
one for cancer recurrence and one for death. This allows us to work
with the data in two different forms, for two different purposes, as
follows:

- Survival outcome data: :: We consider treatment effect estimation in
     the setting where the event of interest is all-cause mortality
     and there are no competing causes.
- Competing risks data: :: We consider treatment effect estimation in
     the setting with two competing causes being cancer recurrence and
     death.

Here we load the =colon= data and create the two datasets above:

#+ATTR_LATEX: :options otherkeywords={}, deletekeywords={}
#+BEGIN_SRC R  :results none :exports code  :session *R* :cache yes  
source("./usage/preprocess.colon.data.R")  
#+END_SRC    

Number of events in the survival data (=colon.surv=): 

#+ATTR_LATEX: :options otherkeywords={}, deletekeywords={}
#+BEGIN_SRC R  :results output :exports results  :session *R* :cache yes  
out <- cbind(colon.surv[, .N, by="event"],   
             colon.surv[, max(time), by="event"][, max.follow.up:=V1][, -c("event", "V1"), with=FALSE])
colnames(out) <- c("event", "N", "max follow-up")
out   
#+END_SRC    

#+RESULTS[<2021-10-26 10:53:24> 7eee5ed3cf7a7dcfa9165d99be6d9864b908f1d8]:
:    event   N max follow-up
: 1:     1 430          2910
: 2:     0 458          3329

Number of events in the competing risks data (=colon.cr=):

#+ATTR_LATEX: :options otherkeywords={}, deletekeywords={}
#+BEGIN_SRC R  :results output :exports results  :session *R* :cache yes  
out <- cbind(colon.cr[order(event)][, .N, by="event"],   
             colon.cr[order(event)][, max(time), by="event"][, max.follow.up:=V1][, -c("event", "V1"), with=FALSE]) 
colnames(out) <- c("event", "N", "max follow-up")
out
#+END_SRC    

#+RESULTS[<2021-10-26 10:59:58> 69107f9b4d0c1b098d8836cf6b851c33986fe64d]:
:   event   N max follow-up
: 1:     0 405          3329
: 2:     1 446          2695
: 3:     2  37          2789

Note that for both datasets we simply removed observations with
missing covariates.


** Simulated version of the =colon= data

The following script sets up functionality to create simulated
versions of the =colon= data:

#+ATTR_LATEX: :options otherkeywords={}, deletekeywords={}
#+BEGIN_SRC R  :results none :exports code  :session *R* :cache yes  
source("./usage/synthesize.colon.data.R")     
#+END_SRC    

To create a simulated version of the survival data, we run code as
follows:

#+ATTR_LATEX: :options otherkeywords={}, deletekeywords={}
#+BEGIN_SRC R :exports both :results output  :session *R* :cache yes 
#-- fit models to data;   
fit.colon <- fit.colon.fun(
    formula.1=Surv(time, event==1)~rx+sex+nodes+differ+age+obstruct+perfor+adhere+extent+surg,
    formula.0=Surv(time, event==0)~rx+sex+nodes+differ+age+obstruct+perfor+adhere+extent+surg,
    formula.treat=rx~sex+age+nodes+differ+obstruct+perfor+adhere+extent+surg,
    d=colon.surv)  
#-- here we simulate data (fixed seed);  
set.seed(15)   
(sim.colon.surv <- synthesize.colon.fun(fit.colon=fit.colon, d=colon.surv, name.treat="rx", event.name="event")) 
#+END_SRC   

#+RESULTS[<2021-10-26 10:48:28> a2e7a0e328f378c138b26ac6c4b3dc5603e36653]:
#+begin_example
     sex age obstruct perfor adhere nodes differ extent surg rx.num      rx      time event
  1:   0  69        0      0      0    12      2      3    0      3 Lev+5FU  634.0321     1
  2:   0  48        0      0      0     1      2      3    0      2     Lev  889.8198     1
  3:   0  42        0      0      0     6      1      3    0      2     Lev  670.7178     1
  4:   0  78        0      0      0     3      2      3    0      3 Lev+5FU 1922.5082     1
  5:   1  49        0      0      0    10      2      3    0      1     Obs 1830.0520     1
 ---                                                                                       
884:   0  75        0      0      0     2      3      3    0      2     Lev  860.8502     1
885:   0  76        0      0      0     1      2      3    0      1     Obs 1527.2115     1
886:   0  51        0      0      0     4      2      3    1      3 Lev+5FU 2665.0731     0
887:   0  63        0      0      0     5      2      3    1      3 Lev+5FU 2577.7704     0
888:   1  51        1      0      0     4      2      3    1      2     Lev 2932.9771     1
#+end_example

To create a simulated version of the competing risks data, we run code
as follows:

#+ATTR_LATEX: :options otherkeywords={}, deletekeywords={}
#+BEGIN_SRC R :exports both :results output  :session *R* :cache yes 
#-- fit models to data; 
fit.colon.cr <- fit.colon.fun(     
    formula.1=Surv(time, event==1)~rx+sex+differ+age+nodes.squared+obstruct+perfor+adhere+extent+surg+rx*sex+rx*perfor+rx*age,
    formula.2=Surv(time, event==2)~rx+sex+nodes+differ+age+obstruct+adhere+extent+surg,
    formula.0=Surv(time, event==0)~rx+sex+nodes+differ+age+obstruct+perfor+adhere+extent+surg,
    formula.treat=rx~sex+age+nodes+differ+obstruct+perfor+adhere+extent+surg,
    d=colon.cr)  
#-- here we simulate data (fixed seed); 
set.seed(31)      
(sim.colon.cr <- synthesize.colon.fun(fit.colon=fit.colon.cr, d=colon.cr, name.treat="rx", event.name="event"))
#+END_SRC   

#+RESULTS[<2021-10-26 10:48:41> da9e677c1c87f49568e8fd420adc172d9d7f5707]:
#+begin_example
     sex age obstruct perfor adhere nodes differ extent surg nodes.squared rx.num      rx      time event
  1:   0  55        1      0      0     4      1      3    0            16      2     Lev 2590.1288     0
  2:   0  64        0      0      0     1      2      3    0             1      2     Lev  862.2267     1
  3:   1  63        0      0      0     2      3      3    0             4      1     Obs  244.6612     1
  4:   1  67        1      0      0     1      2      3    1             1      3 Lev+5FU 1446.1525     1
  5:   0  45        0      0      0     3      2      3    0             9      3 Lev+5FU 3224.6467     0
 ---                                                                                                     
884:   0  71        0      0      0    20      2      3    0           400      3 Lev+5FU 2117.5456     0
885:   0  34        1      0      0     3      1      3    0             9      1     Obs 2314.8256     0
886:   1  66        0      0      0     2      2      4    0             4      1     Obs  488.2843     0
887:   1  50        1      0      1     1      2      3    0             1      2     Lev  127.1821     1
888:   1  42        1      0      0     5      2      3    0            25      1     Obs  525.6158     1
#+end_example

*** True values of target parameters (Box 1)

To compute the approximations to the true values of the target
parameters for the simulated competing risks data, we run the
following code:

#+ATTR_LATEX: :options otherkeywords={}, deletekeywords={}
#+BEGIN_SRC R :exports results :results output  :session *R* :cache yes 
true.a0 <- lapply((1:10)/2, function(tt) synthesize.colon.fun(fit.colon=fit.colon.cr, d=colon.cr, name.treat="rx", event.name="event", 
                                                              n=1e6, get.true.value=0, tau=tt*365.25)) 
true.a1 <- lapply((1:10)/2, function(tt) synthesize.colon.fun(fit.colon=fit.colon.cr, d=colon.cr, name.treat="rx", event.name="event", 
                                                              n=1e6, get.true.value=1, tau=tt*365.25))   
true.a2 <- lapply((1:10)/2, function(tt) synthesize.colon.fun(fit.colon=fit.colon.cr, d=colon.cr, name.treat="rx", event.name="event", 
                                                              n=1e6, get.true.value=2, tau=tt*365.25))
#+END_SRC   


#+ATTR_LATEX: :options otherkeywords={}, deletekeywords={}
#+BEGIN_SRC R :exports results :results output  :session *R* :cache yes 
message("Absolute risks under treatment=Obs:")  
tab0 <- rbind(sapply(true.a0, function(x) x["F1"]), 
              sapply(true.a0, function(x) x["F2"])) 
rownames(tab0) <- c("F1", "F2") 
colnames(tab0) <- paste0((1:10)/2)
print(tab0)
message("")
message("Absolute risks under treatment=Lev:") 
tab1 <- rbind(sapply(true.a1, function(x) x["F1"]), 
              sapply(true.a1, function(x) x["F2"]))
rownames(tab1) <- c("F1", "F2") 
colnames(tab1) <- paste0((1:10)/2) 
print(tab1)
message("")
message("Absolute risks under treatment=Lev+5FU:") 
tab2 <- rbind(sapply(true.a2, function(x) x["F1"]), 
              sapply(true.a2, function(x) x["F2"]))
rownames(tab2) <- c("F1", "F2") 
colnames(tab2) <- paste0((1:10)/2)
print(tab2)
#+END_SRC    

#+RESULTS[<2021-10-26 11:03:24> c713c541118ae841f940cfe9779e4624741a75be]:
#+begin_example
Absolute risks under treatment=Obs:
 
       0.5        1      1.5        2      2.5        3      3.5       4      4.5        5
F1 0.146465 0.227907 0.288342 0.339962 0.382316 0.419372 0.452278 0.48266 0.508024 0.532319
F2 0.000400 0.001145 0.002186 0.003464 0.004639 0.005960 0.007595 0.00901 0.010475 0.011990

Absolute risks under treatment=Lev:
 
       0.5        1      1.5        2      2.5        3      3.5        4      4.5        5
F1 0.137236 0.212368 0.271814 0.320762 0.361983 0.397857 0.430558 0.459212 0.486208 0.509233
F2 0.000235 0.000755 0.001475 0.002178 0.003173 0.004224 0.005209 0.006190 0.007314 0.008595

Absolute risks under treatment=Lev+5FU:
 
       0.5        1      1.5        2      2.5        3      3.5        4      4.5        5
F1 0.088497 0.139775 0.179475 0.214357 0.244999 0.272068 0.296521 0.318285 0.339306 0.357575
F2 0.000180 0.000538 0.001043 0.001834 0.002531 0.003325 0.004253 0.005287 0.006230 0.007313
#+end_example


We see for example that the average treatment effect of levamisole
    treatment compared to no treatment on the cause-one specific
    absolute risk beyond three years is:

#+ATTR_LATEX: :options otherkeywords={}, deletekeywords={}
#+BEGIN_SRC R :exports results :results output  :session *R* :cache yes 
message("Average treatment effect of levamisole compared to no treatment:") 
round(as.numeric(true.a1[(1:10)/2==3][[1]]["F1"] - true.a0[(1:10)/2==3][[1]]["F1"]),4) 
message("")
message("Average treatment effect of levamisole plus fluorouracil compared to no treatment:")  
round(as.numeric(true.a2[(1:10)/2==3][[1]]["F1"] - true.a0[(1:10)/2==3][[1]]["F1"]),4)
#+END_SRC   

#+RESULTS[<2021-10-26 11:07:24> 315f367c8c44acc8387e5babd2376acfe8d2f4ad]:
: Average treatment effect of levamisole compared to no treatment:
: [1] -0.0215
: 
: Average treatment effect of levamisole plus fluorouracil compared to no treatment:
: [1] -0.1473


#+ATTR_LATEX: :options otherkeywords={}, deletekeywords={}
#+BEGIN_SRC R :exports none :results none  :session *R* :cache yes 
library(xtable)
tab0 <- rbind(sapply(true.a0, function(x) x["F1"]), 
              sapply(true.a0, function(x) x["F2"])) 
rownames(tab0) <- c("F1", "F2") 
colnames(tab0) <- paste0((1:10)/2)
print(xtable(tab0, align=rep("c", length(true.a0)+1), digits=3)) 

tab1 <- rbind(sapply(true.a1, function(x) x["F1"]), 
              sapply(true.a1, function(x) x["F2"]))
rownames(tab1) <- c("F1", "F2")  
colnames(tab1) <- paste0((1:10)/2) 
print(xtable(tab1, align=rep("c", length(true.a1)+1), digits=3)) 

tab2 <- rbind(sapply(true.a2, function(x) x["F1"]), 
              sapply(true.a2, function(x) x["F2"]))
rownames(tab2) <- c("F1", "F2") 
colnames(tab2) <- paste0((1:10)/2)
print(xtable(tab2, align=rep("c", length(true.a2)+1), digits=3)) 
#+END_SRC    


*** Targeting hazard estimators for real-valued parameter

We here show the code to apply our TMLE function to target the
real-valued parameter being the absolute risk of cancer relapse after
3 years of follow-up under treatment with levamisole plus
fluorouracil. \\

Note that we simply use a Cox regression including main effects of all
covariates for initial estimation of each cause-specific hazards and
also for the hazard of censoring (specified in the =estimation=
argument, with list elements for each hazard). To estimate the
probability distribution of treatment (specified in the argument
=treat.model=), we similarly include main effects of all
covariates. To get the treatment-specific absolute risk of cancer
relapse under levamisole plus fluorouracil treatment we set the
argument =treat.effect= to ="Lev+5FU"= and the argument =target= to
=1=. We specify the time-horizon by =tau= and note that the time
variable of the data is measured in days. \\

The function returns the initial (untargeted) estimate for the target
parameter, the Kaplan-Meier estimate and the targeted estimate along
with its standard error computed based on the efficient influence
function.


#+ATTR_LATEX: :options otherkeywords={}, deletekeywords={}
#+BEGIN_SRC R :exports code :results none  :session *R* :cache yes 
fit.tmle.F1.Lev5FU.3yrs <- 
     contmle(sim.colon.cr,  
             estimation=list("relapse"=list(fit="cox",
                                            model=Surv(time, event==1)~rx+sex+nodes+age+obstruct+perfor+differ+adhere+extent+surg),
                             "death"=list(fit="cox",
                                          model=Surv(time, event==2)~rx+sex+nodes+age+obstruct+perfor+differ+adhere+extent+surg),
                             "cens"=list(fit="cox",
                                         model=Surv(time, event==0)~rx+sex+nodes+age+obstruct+perfor+differ+adhere+extent+surg)
                             ),
             treat.model=rx~sex+age+nodes+obstruct+perfor+differ+adhere+extent+surg,
             treat.effect="Lev+5FU",   
             output.km=TRUE, 
             target=1,
             tau=3*365.25) 
#+END_SRC   

#+ATTR_LATEX: :options otherkeywords={}, deletekeywords={}
#+BEGIN_SRC R :exports both :results output  :session *R* :cache yes 
fit.tmle.F1.Lev5FU.3yrs
#+END_SRC   

#+RESULTS[<2021-10-26 11:16:28> 4fde8ef84e687d2368b16f764a018467840814f9]:
#+begin_example
$init
$init$F1
         tau=1095.75
init.est  0.30605538
init.se   0.02594074


$km
$km$F1
       tau=1095.75
km.est  0.29184130
km.se   0.02732888


$tmle
$tmle$F1
         tau=1095.75
tmle.est 0.2778811  
tmle.se  0.02584953 
#+end_example


*** Targeting hazard estimators for multivariate parameter

We here show the code to apply our TMLE function to target the
multivariate parameter being the absolute risk of cancer relapse /and/
the absolute risk of relapse-free death after 3 years of follow-up
under treatment with levamisole plus fluorouracil. \\

The only change to the function call above is setting the argument
=target= to =1:2=. (When the argument =target= is multivariate, like
here, the one-step TMLE is applied per default; one could also specify
the argument =iterative= as =TRUE= to apply the iterative TMLE to
target the two absolute risk probabilities separately).

#+ATTR_LATEX: :options otherkeywords={}, deletekeywords={}
#+BEGIN_SRC R :exports code :results none  :session *R* :cache yes 
fit.tmle.F1.F2.Lev5FU.3yrs <- 
     contmle(sim.colon.cr,  
             estimation=list("relapse"=list(fit="cox",
                                            model=Surv(time, event==1)~rx+sex+nodes+age+obstruct+perfor+differ+adhere+extent+surg),
                             "death"=list(fit="cox",
                                          model=Surv(time, event==2)~rx+sex+nodes+age+obstruct+perfor+differ+adhere+extent+surg),
                             "cens"=list(fit="cox",
                                         model=Surv(time, event==0)~rx+sex+nodes+age+obstruct+perfor+differ+adhere+extent+surg)
                             ),
             treat.model=rx~sex+age+nodes+obstruct+perfor+differ+adhere+extent+surg,
             treat.effect="Lev+5FU",   
             output.km=TRUE, 
             target=1:2, 
             tau=3*365.25) 
#+END_SRC   

#+ATTR_LATEX: :options otherkeywords={}, deletekeywords={}
#+BEGIN_SRC R :exports both :results output  :session *R* :cache yes 
fit.tmle.F1.F2.Lev5FU.3yrs
#+END_SRC   

#+RESULTS[<2021-10-26 11:30:48> e6eaf6c7c7fc1bd03323dbac1b68040f140b9467]:
#+begin_example
$init
$init$F1
         tau=1095.75
init.est  0.30605538
init.se   0.02594074

$init$F2
         tau=1095.75
init.est 0.012503259
init.se  0.007945622

$init$S
         tau=1095.75
init.est  0.68144137
init.se   0.02669174


$km
$km$F1
       tau=1095.75
km.est  0.29184130
km.se   0.02732888

$km$F2
       tau=1095.75
km.est 0.014511430
km.se  0.007204259


$tmle
$tmle$F1
         tau=1095.75
tmle.est  0.27774955
tmle.se   0.02584448

$tmle$F2
         tau=1095.75
tmle.est 0.014375801
tmle.se  0.007923176

$tmle$S
         tau=1095.75
tmle.est  0.70787465
tmle.se   0.02660447


$convergenced.at.step
[1] 10
#+end_example


* Dependencies :noexport:

** R-version

The code has been tested with the following R version

#+BEGIN_SRC R  :results output :exports results  :session *R* :cache yes  
version 
#+END_SRC

#+RESULTS[<2021-10-26 09:13:15> 1df30d9c818626e8157399cee494b2b432f3eaf5]:
#+begin_example
               _                           
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          4                           
minor          0.3                         
year           2020                        
month          10                          
day            10                          
svn rev        79318                       
language       R                           
version.string R version 4.0.3 (2020-10-10)
nickname       Bunny-Wunnies Freak Out
#+end_example

and the following package versions:

#+BEGIN_SRC R  :results output raw drawer  :exports results  :session *R* :cache yes  
pp <- c("data.table", "zoo", "glmnet", "stringr", "nleqslv", "prodlim", "ggplot2", "gridExtra", "survival", "riskRegression")
Publish::org(data.table(Package=pp,Version=sapply(pp,function(x) as.character(packageVersion(x)))))
#+END_SRC

#+RESULTS[<2021-10-26 09:16:52> d8d1bcae67f94c7406bb1a22603134875ff22f9c]:
:results:
| Package    | Version |
|------------+---------|
| data.table |  1.13.0 |
| zoo        |   1.8.8 |
| stringr    |   1.4.0 |
| ltmle      |   1.2.0 |
| parallel   |   4.0.2 |
| foreach    |   1.5.0 |
| doParallel |  1.0.15 |
:end:
